/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArrivalSchema extends BaseModel {
  static $columns = ['busId', 'createdAt', 'etaMinutes', 'id', 'stationId', 'updatedAt'] as const
  $columns = ArrivalSchema.$columns
  @column()
  declare busId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare etaMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare stationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BusSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'latitude', 'longitude', 'occupancyLevel', 'passengerCount', 'plate', 'routeId', 'status', 'updatedAt'] as const
  $columns = BusSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column()
  declare longitude: number | null
  @column()
  declare occupancyLevel: string
  @column()
  declare passengerCount: number
  @column()
  declare plate: string
  @column()
  declare routeId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RouteStationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'routeId', 'sequenceOrder', 'stationId', 'updatedAt'] as const
  $columns = RouteStationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare routeId: number
  @column()
  declare sequenceOrder: number
  @column()
  declare stationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RouteSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'schedule', 'updatedAt'] as const
  $columns = RouteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare schedule: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'latitude', 'location', 'longitude', 'name', 'occupancyLevel', 'passengerCount', 'updatedAt'] as const
  $columns = StationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: number | null
  @column()
  declare location: string | null
  @column()
  declare longitude: number | null
  @column()
  declare name: string
  @column()
  declare occupancyLevel: string
  @column()
  declare passengerCount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WhatsappChatSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'id', 'lastMessage', 'phoneNumber', 'updatedAt'] as const
  $columns = WhatsappChatSchema.$columns
  @column()
  declare context: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastMessage: string | null
  @column()
  declare phoneNumber: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
